
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { useRouter } from 'next/router'

interface Restaurant {
    name: string;
    image: string;
    rating: number;
    liked: boolean;
}

export default function Home() {
    const router = useRouter();
    const query = router.query;
    const city = query.city;

    const restaurants: Restaurant[] = [
        {
            name: "Restaurant 1",
            image: "/images/sanfrancisco.webp",
            rating: 5,
            liked: true
        },
        {
            name: "Restaurant 2",
            image: "/images/sanjose.webp",
            rating: 3.5,
            liked: true
        },
        {
            name: "Restaurant 3",
            image: "/images/sandiego.webp",
            rating: 5,
            liked: false
        },
        {
            name: "Restaurant 4",
            image: "/images/losangeles.webp",
            rating: 4,
            liked: false
        },
        {
            name: "Restaurant 5",
            image: "/images/newyork.webp",
            rating: 5,
            liked: false
        }
    ]

    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <p className={styles.description}>
                    Top Restaurants In...
                </p>

                <h1 className={styles.title}>
                    {city}
                </h1>



                <div className={styles.grid}>
                    {restaurants.map((restaurant) => (
                        <Link
                            href={{
                                pathname: "/detail",
                                query: { restaurant: restaurant.name }
                            }}
                            key={restaurant.name}
                        >
                            <div
                                className={styles.card}
                                style={{
                                    backgroundImage: `url(${restaurant.image})`,
                                    boxShadow: restaurant.liked ? "0 0 3rem green" : "none"

                                }}>
                                <div className={styles.cardContent}>
                                    <h3>{restaurant.name}</h3>
                                    <p>{restaurant.rating}</p>
                                </div>
                            </div>
                        </Link>
                    ))}



                </div>
            </main>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{' '}
                    <span className={styles.logo}>
                        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
                    </span>
                </a>
            </footer>
        </div>
    )
}
