import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

interface City {
  name: string;
  image: string;
}

export default function Home() {

  const cities: City[] = [
    {
      name: "San Francisco",
      image: "/images/sanfrancisco.webp"
    },
    {
      name: "San Jose",
      image: "/images/sanjose.webp"
    },
    {
      name: "San Diego",
      image: "/images/sandiego.webp"
    },
    {
      name: "Los Angeles",
      image: "/images/losangeles.webp"
    },
    {
      name: "New York",
      image: "/images/newyork.webp"
    }


  ]


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Featured Cities
        </h1>

        <p className={styles.description}>
          Click a location to see top nearby restaurants!
        </p>

        <div className={styles.grid}>

          {cities.map((city) => (
            <Link href="/businesses" key={city.name}>
              <div className={styles.card} style={{ backgroundImage: `url(${city.image})` }}>
                <div className={styles.cardContent}>
                  <h2>{city.name}</h2>
                  {/* <p>Find in-depth information about Next.js features and API.</p> */}
                </div>
              </div>
            </Link>
          ))}


        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
